types:
  - value: "feat: :sparkles:"
    name: "feat:     æ–°æ©Ÿèƒ½ã®è¿½åŠ  âœ¨"
  - value: "feat: :boom:"
    name: "feat:     äº’æ›æ€§ã‚’ç ´å£Šã™ã‚‹ã‚ˆã†ãªæ©Ÿèƒ½ã®å¤‰æ›´ãƒ»å‰Šé™¤ã‚’ã™ã‚‹æ™‚ ğŸ’¥"
  - value: "feat: :lock:"
    name: "feat:     ã‚»ã‚­ãƒ¥ãƒªãƒ†ã‚£å‘ä¸Š ğŸ”’ï¸"
  - value: "feat: :tada:"
    name: "feat:     åˆå›ã‚³ãƒŸãƒƒãƒˆ ğŸ‰"
  - value: "fix: :bug:"
    name: "fix:      ãƒã‚°ä¿®æ­£ ğŸ›"
  - value: "fix: :ambulance:"
    name: "fix:      ç·Šæ€¥ã®ãƒã‚°ä¿®æ­£ ğŸš‘ï¸"
  - value: "docs: :memo:"
    name: "docs:     ãƒ‰ã‚­ãƒ¥ãƒ¡ãƒ³ãƒˆã®ã¿ã®å¤‰æ›´ ğŸ“"
  - value: "style: :art:"
    name: "style:    ã‚³ãƒ¼ãƒ‰ã®å‹•ä½œã«å½±éŸ¿ã—ãªã„ã€è¦‹ãŸç›®ã ã‘ã®å¤‰æ›´ ğŸ¨"
  - value: "refactor: :recycle:"
    name: "refactor: ãƒã‚°ä¿®æ­£ã‚„æ©Ÿèƒ½è¿½åŠ ã§ã¯ãªã„ã‚³ãƒ¼ãƒ‰ã®å¤‰æ›´ â™»"
  - value: "perf: :zap:"
    name: "perf:     ãƒ‘ãƒ•ã‚©ãƒ¼ãƒãƒ³ã‚¹ã‚’å‘ä¸Šã•ã›ã‚‹ã‚³ãƒ¼ãƒ‰ã®å¤‰æ›´ âš¡"
  - value: "test: :white_check_mark:"
    name: "test:     ä¸è¶³ã—ã¦ã„ã‚‹ãƒ†ã‚¹ãƒˆã®è¿½åŠ ã¾ãŸã¯æ—¢å­˜ã®ãƒ†ã‚¹ãƒˆã®ä¿®æ­£ âœ…"
  - value: "ci: :green_heart:"
    name: "ci:       CIã®è¨­å®šãƒ»æ”¹å–„ ğŸ’š"
  - value: "chore: :wrench:"
    name: "chore:    æ§‹æˆãƒ•ã‚¡ã‚¤ãƒ«ãƒ»è¨­å®šãƒ•ã‚¡ã‚¤ãƒ«ã‚’è¿½åŠ ã—ãŸã‚Šæ›´æ–°ã—ãŸã¨ãã«ä½¿ã„ã¾ã™ ğŸ”§"
  - value: "chore: :package:"
    name: "chore:    ãƒ‘ãƒƒã‚±ãƒ¼ã‚¸ã®ã‚¤ãƒ³ã‚¹ãƒˆãƒ¼ãƒ«ãƒ»ã‚¢ãƒ³ã‚¤ãƒ³ã‚¹ãƒˆãƒ¼ãƒ« ğŸ“¦"
  - value: "revert: :rewind:"
    name: "revert:   ä»¥å‰ã®ã‚³ãƒŸãƒƒãƒˆã‚’å…ƒã«æˆ»ã—ã¾ã™ âª"

messages:
  type: ã‚¿ã‚¤ãƒ—ã¨çµµæ–‡å­—ã‚’é¸æŠã—ã¦ãã ã•ã„
  subject: ã‚³ãƒŸãƒƒãƒˆå†…å®¹ã«ã¤ã„ã¦å…¥åŠ›ã—ã¦ãã ã•ã„
  ticket_number: Redmineã®Issueç•ªå·ã‚’å…¥åŠ›ã—ã¦ãã ã•ã„
  confirm_commit: ä¸‹è¨˜ã®å†…å®¹ã§ã‚³ãƒŸãƒƒãƒˆã‚’ç¶™ç¶šã—ã¦ã‚‚ã‚ˆã‚ã—ã„ã§ã™ã‹ï¼Ÿ

skip_questions:
  - scope
  - body
  - breaking
  - footer

allow_breaking_changes:
  - feat
  - fix

ticket_number:
  enable: false
  required: true
  prefix: "#"
  match_pattern: "\\d+"

  from_branch_name:
    enable: true
    extract_regexp: "^.+?\\/(?P<ticket_number>\\d+)([-_]\\w+)*$"
